 UPDATE PUBLIC.CERTIFICATION   SET hours = 100 , description = 'Exam AZ-900' , weight = 33  WHERE NAME = 'AZ-900: Microsoft Azure Fundamentals'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 150 , description = 'Exam AZ-204' , weight = 50  WHERE NAME = 'AZ-204: Developing Solutions for Microsoft Azure'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 150 , description = 'Certifikim per rreshtin 35 ; AZ-204' , weight = 50  WHERE NAME = 'Azure Developer Associate'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 150 , description = 'Exam AZ-104' , weight = 50  WHERE NAME = 'AZ-104: Microsoft Azure Administrator'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 150 , description = 'Exam DP-203' , weight = 50  WHERE NAME = 'Azure Data Engineer Associate'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 250 , description = 'Exam AZ-303;Exam AZ-304' , weight = 83  WHERE NAME = 'Azure Solutions Architect Expert'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 100 , description = 'Exam 98-383' , weight = 33  WHERE NAME = 'MTA: Introduction to Programming Using HTML and CSS'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 100 , description = 'Exam 98-364' , weight = 33  WHERE NAME = 'MTA: Database Fundamentals'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 100 , description = 'Exam 98-361' , weight = 33  WHERE NAME = 'MTA: Software Development Fundamentals'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 200 , description = '' , weight = 66  WHERE NAME = 'AWS Certified Developer (Associate)'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 150 , description = '' , weight = 50  WHERE NAME = 'AWS Certified Cloud Practitioner'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'SAS Certified Associate Programming Fundamentals Using SAS 9.4'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'SAS Certified Specialist Base Programming Using SAS 9.4'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'IBM FileNet Business Process Manager-Designer 4.5'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'IBM FileNet Business Process Manager-Developer 4.5'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'IBM FileNet Content Manager-Administrator 4.5'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'IBM FileNet Content Manager-Designer 4.5'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'IBM FileNet Content Manager-Developer 4.5'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Data Science'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 200 , description = '' , weight = 66  WHERE NAME = 'MySQL 5.6 Database Administrator'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 150 , description = '' , weight = 50  WHERE NAME = 'MySQL 5.6 Developer'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 100 , description = '' , weight = 33  WHERE NAME = 'Oracle DB Administration - Brainbanch'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 50 , description = '' , weight = 16  WHERE NAME = 'RDBMS Concepts - Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 150 , description = 'Exam 1Z0-803' , weight = 50  WHERE NAME = 'OCA: Oracle Certified Associate, Java SE 7 Programmer Certification'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 150 , description = 'Exam 1Z0-808, 1Z0-809' , weight = 50  WHERE NAME = 'OCA: Oracle Certified Associate, JAVA SE 8 Programmer'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 200 , description = 'Exam 1Z0-900' , weight = 66  WHERE NAME = 'OCP: Oracle Certified Professional, Java EE 7 Application Developer'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'OCP-JAVA SE 8 Programmer'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 250 , description = 'Exam 1Z0-819' , weight = 83  WHERE NAME = 'OCP-JAVA SE 11 Developer'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 300 , description = 'Exam VMware EDU-1202' , weight = 100  WHERE NAME = 'Spring Professional'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 80 , description = '' , weight = 26  WHERE NAME = 'Programming in HTML5 with JavaScript and CSS3 Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 120 , description = '' , weight = 40  WHERE NAME = 'Arcitura SOA Professional'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 100 , description = 'Testing' , weight = 33  WHERE NAME = 'ISTQB Foundation Level Certification (CTFL)'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 80 , description = '' , weight = 26  WHERE NAME = 'WebAssembler.NET'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 80 , description = '' , weight = 26  WHERE NAME = 'Client/Server Concepts - Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 80 , description = '' , weight = 26  WHERE NAME = 'Web Services Concepts - Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 80 , description = '' , weight = 26  WHERE NAME = 'Web Development Concepts - Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 50 , description = '' , weight = 16  WHERE NAME = 'Software Quality Assurance, Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 80 , description = '' , weight = 26  WHERE NAME = 'International Software Test Institute™'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 50 , description = '' , weight = 16  WHERE NAME = 'Software Testing Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 100 , description = '' , weight = 33  WHERE NAME = 'PHP 5.6 - Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 80 , description = '' , weight = 26  WHERE NAME = 'Training Development Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 50 , description = 'Brainbranch' , weight = 16  WHERE NAME = 'UX Concepts'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Software Business Analysis Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'PMI Professional in Business Analysis (PMI-PBA) ®'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Entry Certificate in Business Analysis (ECBA™)'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'OCUP 2 Foundation Level'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'OMG CERTIFIED EXPERT IN BPM™ 2 (OCEB™ 2)'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 150 , description = 'Exam PL-900' , weight = 50  WHERE NAME = 'Power Platform Fundamentals'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Project Management Professional (PMP)'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 120 , description = '' , weight = 40  WHERE NAME = 'Project+ CompTIA Certified'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Project Management & Agile Fundamentals'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Agile Scrum Foundation'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Professional Scrum Master, Scrum.org – PSMI'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Professional Scrum Product Owner I'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Agile in one day'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'PMI Agile Certified Practitioner'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Scrum Fundamentals Certified'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 100 , description = '' , weight = 33  WHERE NAME = 'ITIL Foundation Certificate in IT Service Management'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 100 , description = '' , weight = 33  WHERE NAME = 'ITIL V4 Foundation'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 200 , description = '' , weight = 66  WHERE NAME = 'Deep Learning Fundamentals'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 150 , description = '' , weight = 50  WHERE NAME = 'Introduction to neural Networks and Deep Learning'
 UPDATE PUBLIC.CERTIFICATION   SET hours = 200 , description = '' , weight = 66  WHERE NAME = 'Neural Networks and Deep Learning'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'System Architect'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Information Technology Security Fundamentals'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'TAA Information Security Awareness Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Nuxeo Admin Advanced Certificate'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Nuxeo Backend Certification'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Nuxeo Studio Advanced Certification'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Linux Foundation Certified System Administrator (LFCS)'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Linux Administration Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MTCNA - MikroTik Certified Network Associate'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'NSE1 Network Security Associate'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'NSE2 Network Security Associate'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'CCNA - Cisco Certified Network Associate'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Vmware vSphere 5 Brainbench'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'CMMI (Capability Maturity Model Integration) Associate'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Introduction to Marketing'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Introduction to Financial Accounting'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MTA - Microsoft Technical Associate'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Developing SQL Databases'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Querying Data with Transact-SQL'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCS: Microsoft Certified Specialist: Programming in HTML5 with JavaScript and CSS3'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCP: Microsoft Certified Professional'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Developing ASP.NET MVC Web Applications'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Developing Microsoft Azure and Web Services'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Microsoft Certified Solutions Developer: Web Applications'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCSA: Web Applications'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCSD: Microsoft Certified Solutions Developer: App Builder'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MS: Microsoft Specialist: Programming in C#'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCSA: Microsoft® Certified Solutions Associate: SQL Server 2012/2014'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCSA: SQL 2016 Database Development'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCSE: Microsoft® Certified Solutions Expert: Data Management and Analytics'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Administering Microsoft SQL Server 2012/2014 Databases'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCPD: Microsoft® Certified Professional Developer: Web Developer 4'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCSE: Microsoft® Certified Solutions Expert: Data Platform'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCTS: Microsoft® Certified Technology Specialist: .NET Framework 4, Service Communication Applications'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCTS: Microsoft® Certified Technology Specialist: Microsoft Biztalk Server 2010'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Microsoft Certified Technology Specialist  .Net Framework 4, Data Access'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Microsoft Certified Technology Specialist .Net Framework 4, Web Application'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Querying Microsoft SQL Server 2012/2014'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCSE: Microsoft® Certified Solutions Expert: Data Management and Analytics (Charter)*'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCTS: Microsoft® Certified Technology Specialist: SQL Server 2008, Implementation and Maintenance'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'Microsoft® Certified IT Professional: Database Developer 2008'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MS SQL Server 2014 Reporting Services'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MS Windows Server 2012 Administration'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'SQL Server 2014 Administration'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCSA: SQL 2016 Database Administration'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'MCPD: Microsoft Certified Technology Specialist: Sharepoint 2010, Application Development'
 UPDATE PUBLIC.CERTIFICATION   SET hours = -1 , description = '' , weight = -1  WHERE NAME = 'EE 6 Java Persistence API Developer'
